### ISSUE TITLE
[Question] Handle old version(s) of OS/2 tables

### ISSUE THREAD

**Issue by all-things-liquid** [fontello/ttf2eot#9]
I've recently encountered issues with a font that did not specify `ulCodePageRange1` and `ulCodePageRange2`, which conflicts with [this part of ttf2eot](https://github.com/fontello/ttf2eot/blob/992f09821dda18e659f4d0bbc4a3979a1d9ffbb6/index.js#L156) and gives me the following error:

```
internal/buffer.js:81 throw new ERR_OUT_OF_RANGE(type || 'offset',
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 74. Received 78 
  at boundsError (internal/buffer.js:81:9) at Buffer.readUInt32BE (internal/buffer.js:304:5) 
  at ttf2eot (/usr/local/lib/node_modules/ttf2eot/index.js:157:34) 
  at Object.<anonymous> (/usr/local/lib/node_modules/ttf2eot/ttf2eot.js:63:11) 
  at Module._compile (internal/modules/cjs/loader.js:1015:30) 
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10) 
  at Module.load (internal/modules/cjs/loader.js:879:32) 
  at Function.Module._load (internal/modules/cjs/loader.js:724:14) 
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) 
  at internal/main/run_main_module.js:17:47 
  { code: 'ERR_OUT_OF_RANGE' } 
```

I've seen that version 0 of OS/2 tables doesn't specify these 2 parameters, would it be suitable to wrap this loop in a statement that checks the table version? (I can submit a PR for that if this is out of the the use cases you currently have for this project)

**Comment by puzrin** [comment]
To be honest, EOT are very ancient, and i don't like to spent time for this project improve.

BUT, if you wish to make PR, and can keep old behaviour intact - i see no problem to merge. IMO your proposal for OS/2 table version check looks reasonable.
